# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from . import favourite_pb2 as favourite__pb2
from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2


class FavouriteStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetFavList = channel.unary_unary(
                '/Favourite/GetFavList',
                request_serializer=favourite__pb2.FavRequest.SerializeToString,
                response_deserializer=favourite__pb2.FavListResponse.FromString,
                )
        self.AddFav = channel.unary_unary(
                '/Favourite/AddFav',
                request_serializer=favourite__pb2.FavRequest.SerializeToString,
                response_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                )
        self.DeleteFav = channel.unary_unary(
                '/Favourite/DeleteFav',
                request_serializer=favourite__pb2.FavRequest.SerializeToString,
                response_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                )
        self.GetFavDetail = channel.unary_unary(
                '/Favourite/GetFavDetail',
                request_serializer=favourite__pb2.FavRequest.SerializeToString,
                response_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                )


class FavouriteServicer(object):
    """Missing associated documentation comment in .proto file."""

    def GetFavList(self, request, context):
        """过滤收藏信息
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def AddFav(self, request, context):
        """添加用户收藏
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DeleteFav(self, request, context):
        """删除用户收藏
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetFavDetail(self, request, context):
        """获取用户收藏详情
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_FavouriteServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetFavList': grpc.unary_unary_rpc_method_handler(
                    servicer.GetFavList,
                    request_deserializer=favourite__pb2.FavRequest.FromString,
                    response_serializer=favourite__pb2.FavListResponse.SerializeToString,
            ),
            'AddFav': grpc.unary_unary_rpc_method_handler(
                    servicer.AddFav,
                    request_deserializer=favourite__pb2.FavRequest.FromString,
                    response_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            ),
            'DeleteFav': grpc.unary_unary_rpc_method_handler(
                    servicer.DeleteFav,
                    request_deserializer=favourite__pb2.FavRequest.FromString,
                    response_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            ),
            'GetFavDetail': grpc.unary_unary_rpc_method_handler(
                    servicer.GetFavDetail,
                    request_deserializer=favourite__pb2.FavRequest.FromString,
                    response_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'Favourite', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class Favourite(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def GetFavList(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/Favourite/GetFavList',
            favourite__pb2.FavRequest.SerializeToString,
            favourite__pb2.FavListResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def AddFav(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/Favourite/AddFav',
            favourite__pb2.FavRequest.SerializeToString,
            google_dot_protobuf_dot_empty__pb2.Empty.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def DeleteFav(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/Favourite/DeleteFav',
            favourite__pb2.FavRequest.SerializeToString,
            google_dot_protobuf_dot_empty__pb2.Empty.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetFavDetail(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/Favourite/GetFavDetail',
            favourite__pb2.FavRequest.SerializeToString,
            google_dot_protobuf_dot_empty__pb2.Empty.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
