# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: favourite.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0f\x66\x61vourite.proto\x1a\x1bgoogle/protobuf/empty.proto\"-\n\nFavRequest\x12\x0e\n\x06userId\x18\x01 \x01(\x05\x12\x0f\n\x07goodsId\x18\x02 \x01(\x05\".\n\x0b\x46\x61vResponse\x12\x0e\n\x06userId\x18\x01 \x01(\x05\x12\x0f\n\x07goodsId\x18\x02 \x01(\x05\"<\n\x0f\x46\x61vListResponse\x12\r\n\x05total\x18\x01 \x01(\x05\x12\x1a\n\x04\x64\x61ta\x18\x02 \x03(\x0b\x32\x0c.FavResponse2\xce\x01\n\tFavourite\x12+\n\nGetFavList\x12\x0b.FavRequest\x1a\x10.FavListResponse\x12-\n\x06\x41\x64\x64\x46\x61v\x12\x0b.FavRequest\x1a\x16.google.protobuf.Empty\x12\x30\n\tDeleteFav\x12\x0b.FavRequest\x1a\x16.google.protobuf.Empty\x12\x33\n\x0cGetFavDetail\x12\x0b.FavRequest\x1a\x16.google.protobuf.EmptyB\nZ\x08./;protob\x06proto3')



_FAVREQUEST = DESCRIPTOR.message_types_by_name['FavRequest']
_FAVRESPONSE = DESCRIPTOR.message_types_by_name['FavResponse']
_FAVLISTRESPONSE = DESCRIPTOR.message_types_by_name['FavListResponse']
FavRequest = _reflection.GeneratedProtocolMessageType('FavRequest', (_message.Message,), {
  'DESCRIPTOR' : _FAVREQUEST,
  '__module__' : 'favourite_pb2'
  # @@protoc_insertion_point(class_scope:FavRequest)
  })
_sym_db.RegisterMessage(FavRequest)

FavResponse = _reflection.GeneratedProtocolMessageType('FavResponse', (_message.Message,), {
  'DESCRIPTOR' : _FAVRESPONSE,
  '__module__' : 'favourite_pb2'
  # @@protoc_insertion_point(class_scope:FavResponse)
  })
_sym_db.RegisterMessage(FavResponse)

FavListResponse = _reflection.GeneratedProtocolMessageType('FavListResponse', (_message.Message,), {
  'DESCRIPTOR' : _FAVLISTRESPONSE,
  '__module__' : 'favourite_pb2'
  # @@protoc_insertion_point(class_scope:FavListResponse)
  })
_sym_db.RegisterMessage(FavListResponse)

_FAVOURITE = DESCRIPTOR.services_by_name['Favourite']
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'Z\010./;proto'
  _FAVREQUEST._serialized_start=48
  _FAVREQUEST._serialized_end=93
  _FAVRESPONSE._serialized_start=95
  _FAVRESPONSE._serialized_end=141
  _FAVLISTRESPONSE._serialized_start=143
  _FAVLISTRESPONSE._serialized_end=203
  _FAVOURITE._serialized_start=206
  _FAVOURITE._serialized_end=412
# @@protoc_insertion_point(module_scope)
